#!/usr/bin/env bash
# Concatenate the self-play engine into ONE browser script (worker/az_bundle.js) for the Web Worker.
# build.sh in cribbage-trainer is JSX/React-only; this is the plain-JS path: cat in dependency order,
# stripping Node plumbing (require/module.exports, the fs+Function-factory in az_game.js, and each
# file's `if (require.main === module)` self-test tail). Duplicate top-level `const NPOL`/`cardId`
# across modules would collide in one scope, so those are stripped and NPOL is injected once (cardId
# comes from src/engine.js).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/worker/az_bundle.js"
mkdir -p "$ROOT/worker"

# truncate at the self-test guard, then drop Node-only / colliding lines
strip() {
  awk '/if \(require\.main === module\)/{exit} {print}' "$1" \
    | grep -vE '^#!|require\(|module\.exports|fs\.readFileSync|new Function\(eng|^const NPOL =|^const cardId ='
}

{
  echo "/* GENERATED by engine/build-bundle.sh — do not edit. Cribbage Zero self-play bundle (browser). */"
  echo '"use strict";'
  cat       "$ROOT/src/engine.js"        # browser-safe scoring; provides cardId, pval, scoreInto, pegScore…
  echo 'const NPOL = 15;'                # single canonical copy (was duplicated across az_mcts/game/common)
  strip     "$ROOT/engine/az_net.js"     # class Net
  strip     "$ROOT/engine/az_mcts.js"    # function search (uses Net)
  strip     "$ROOT/engine/az_game.js"    # class CribGame (scoring now from engine.js above)
  strip     "$ROOT/engine/az_common.js"  # selfPlay/train/net (de)serialization helpers
  strip     "$ROOT/engine/az_sync.js"    # makeSync (Worker-API client)
} > "$OUT"

# sanity: the public surface is present, and it parses
for name in 'function scoreInto' 'class Net' 'function search' 'class CribGame' 'function selfPlay' 'function makeSync'; do
  grep -q "$name" "$OUT" || { echo "BUNDLE MISSING: $name"; exit 1; }
done
node --check "$OUT"
echo "built $OUT ($(wc -l < "$OUT") lines)"
